### ISSUE TITLE
Combine plus-PFP database with Rhinoplant database from Kees and upload to galaxy

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/installed-tools#28]

**Comment by Dirowa** [comment]
@hexylena Hi, i had a small meeting with Kees about he wanted (I believe it is for Kraken2 (yay easy datamanager)). but he also wants te database be uploaded in general like reference data.

what he wants:
combine his fasta file about..... rhino plants? with the plus PFP 16 database (https://benlangmead.github.io/aws-indexes/k2).
so i think it would be easiest to combine the fasta variant with his fasta file, so i have to convert that first

**Comment by hexylena** [comment]
Thanks @Dirowa for the details! Ok, that does sound easy enough :)  We should think about where to store such databases and whether they should be updated automatically.

**Comment by Dirowa** [comment]
hi @hexylena.
I was thinking to do the following:
- upload by kraken data managers
- make the fasta file a reference data set, public available for everyone in galaxy ( I remember a tutorial for that)
- The manual dataset will be stored somewhere on a computer (* should we make a github for that so we can find everything easily back?

**Comment by hexylena** [comment]
1. Yes, kraken DM is clear, for that we'll just use that.
2. Ok, a data library sounds good!

**Comment by Dirowa** [comment]
just to notify or for later use

the Kraken2-build is quite broken and maintained dont put much effort into it.

Fix the retrieve database  in libexec/rsync_from_ncbi.pl
change ```"^ftp://"  ````by  ```` "^https:// " ````  in line 46


add this if statement in the forloop on line 45

```
if ( $full_path =~/^na/){
next
}
````

meaning that the database will not be quite complete due missing data
source = https://github.com/DerrickWood/kraken2/issues/226

**Comment by hexylena** [comment]
ncbi shut off their FTP servers within the past 2 months, fwiw. It's a recent change.

**Comment by Dirowa** [comment]
Oh really, i wasnt aware of it. luckly it could be easily fixed

**Comment by Dirowa** [comment]
just to gain a clear task list:

- [x] Download library's
- [x] Add cutom fasta file to library
- [ ] Build database
- [ ] Debug database builder (it is either Ram shortage or error in the code, xargs: cat: terminated by signal 13
- [ ] Upload database to new galaxy

**Comment by Dirowa** [comment]
Hi @hexylena , I think it should be time to enable the custom created database to galaxy. 

I tried enabling it with editing this file ```//srv/galaxy/var/tool-data/kraken2_databases.loc```
which is now:
```
# Expect three columns, tab separated, as follows:
# - value (Galaxy records this in the Galaxy DB)
# - name (Galaxy shows this in the UI)
# - path with or without trailing slash (folder name containing the Kraken DB)
#
# e.g.
# plants2018<tab>Plant genomes (2018)<tab>/path/to/krakenDB/plants_2018
plusPFP_full+exstra     full kraken2 PFP database with custome plant index (2021)       //data/databases/kees_kraken2_database/
```

After I restarted the server but the database does now show up. did I make a syntax error or used the wrong documentation for this?

Extra info *
database size total 375 gb
size of library 217 gb
size of hash.k2d 125 gb

**Comment by hexylena** [comment]
I guess this is resolved? Awesome!

**Comment by Dirowa** [comment]
indeed. i also tested the database on galaxy and it works great. Later today will I help kees with usingit
