### ISSUE TITLE
not all tools are installing on galaxy

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/installed-tools#30]

**Comment by Dirowa** [comment]
problem:
Laura notified me that not all tools are in the new galaxy server.

observations:

not all tools in tools.yaml are in the galaxy server
when checking jenkins, not all tools will even be mentioned which are in tools.yaml.
When rerunning jenkins. it will see the last installed tools again as new tools to install.
Questions:
Any idea where to look into @hexylena, i checkt the makefile and the scripts but this seem to be correct. Is there some sort of version which is not uploaded correctly?

**Comment by hexylena** [comment]
this looks right.
https://galaxy.atgm.avans.nl/jenkins/job/install-tools/1692/console

the last tool change was fixing the username of `muscle` and this appears in the log correctly:

```
(61/75) repository muscle already installed at revision 533b3b2a1e66. Skipping.
```

**Comment by hexylena** [comment]
https://galaxy.atgm.avans.nl/root?tool_id=toolshed.g2.bx.psu.edu/repos/crs4/muscle/muscle/0.0.11 and muscle is indeed installed properly

**Comment by hexylena** [comment]
>  Laura notified me that not all tools are in the new galaxy server.

@Laurax491 do you have specific examples of missing tools?

**Comment by hexylena** [comment]
ok I see e.g. `velvet` is skipped. It seems the `lock` file is not getting updated.

**Comment by hexylena** [comment]
```
INFO:root:Fetching updates for florianbegusch/qiime2_suite
Traceback (most recent call last):
  File "scripts/update-tool.py", line 72, in <module>
    update_file(args.fn.name, owner=args.owner, name=args.name, without=args.without)
  File "scripts/update-tool.py", line 41, in update_file
    latest_rev = revs[-1]
IndexError: list index out of range
```

the fix script does not finish OK. `suites` should NEVER be used (it's a really stupid galaxy bug that really drives me insane) but yeah. please list out individual tools from a suite you want installed, suites have always been broken.

**Comment by Laurax491** [comment]
I know DESeq2 and Annotate DESeq2/DEXseq output tables are missing. Also the category RNA analysis is missing which is present in the old Galaxy server.

**Comment by hexylena** [comment]
https://galaxy.atgm.avans.nl/jenkins/job/install-tools/1694/console it should be fixed now. Thanks @Laurax491 !!
